baseURL: "https://uj-gym-ad.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Get your body UJ"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Get your body UJ"
  description: "work that summer body while at school"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Uj Gym Auckland Park"
    # - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "gym@uj.ac.za"
    - "011.555.0119"

  copyright: "© 2022 Get your body UJ All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Sign Up Now"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
