name = "up-business-theme"
license = "MIT"
licenselink = "https://gitlab.com/writeonlyhugo/up-business-theme/-/blob/master/LICENSE"
description = "A clean and modern landing page website inspired by clean and modern illustrations."


tags = ["blog", "responsive", "personal", "light", "bootstrap", "portfolio", "landing", "company", "modern"]
features = []

[author]
  name = "Iago Bozza"
